name: Deploy History Service
on:
  push:
    branches:
      - master
    paths:
      - "backend-services/user-backend-service/**"
  workflow_dispatch:

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-service-to-eb-staging.yml
    with:
      service_name: history-service
      service_path: backend-services/history-backend-service
      application_name: peerprep-staging-history-service
      environment_name: peerprep-staging-history-service
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}

  deploy-prod:
    uses: ./.github/workflows/deploy-service-to-eb-prod.yml
    with:
      service_name: history-service
      service_path: backend-services/history-backend-service
      application_name: peerprep-history-service
      environment_name: peerprep-history-service-prod
    secrets: inherit
