name: Deploy Collab Service
on:
  push:
    branches:
      - master
    paths:
      - "backend-services/chatting-backend-service/**"
  workflow_dispatch:

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-service-to-eb-staging.yml
    with:
      service_name: chat-service
      service_path: backend-services/chatting-backend-service
      application_name: peerprep-staging-chat-service
      environment_name: peerprep-staging-chat-service
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}

  deploy-prod:
    uses: ./.github/workflows/deploy-service-to-eb-prod.yml
    with:
      service_name: chat-service
      service_path: backend-services/chatting-backend-service
      application_name: peerprep-chat-service
      environment_name: peerprep-chat-service-prod
    secrets: inherit
