name: Deploy Collab Service
on:
  push:
    branches:
      - master
      - setup-terraform
    paths:
      - "backend-services/collab-backend-service/**"
  workflow_dispatch:

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-service-to-eb-staging.yml
    with:
      service_name: collab-service
      service_path: backend-services/collab-backend-service
      application_name: peerprep-staging-collab-service
      environment_name: peerprep-staging-collab-service
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
  deploy-prod:
    uses: ./.github/workflows/deploy-service-to-eb-prod.yml
    with:
      service_name: collab-service
      service_path: backend-services/collab-backend-service
      application_name: peerprep-collab-service
      environment_name: peerprep-collab-service-prod
    secrets: inherit
